source 'https://rubygems.org'

gem 'pry'
gem 'mongo_mapper'
gem 'bson_ext'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'json'
gem 'omniauth'
gem 'omniauth-oauth2'
gem 'omniauth-github'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'heroku'
gem 'thin'
